
CREATE OR REPLACE 
PACKAGE MAINTANCE_CLIENT AS 

  FUNCTION CC_Expire_Date (FlagReturn varchar2)
  RETURN VARCHAR2;

END MAINTANCE_CLIENT;
 
 
 
 
CREATE OR REPLACE PACKAGE BODY MAINTANCE_CLIENT AS 
   ActualDate sysdate; 
   
FUNCTION CC_Expire_Date (FlagReturn varchar2)
   RETURN varchar2 IS 
      FlagReturn varchar2; 

BEGIN

	UPDATE CLIENT_DATA
	SET	Valid = 0
	WHERE CC_Expire_Date < sysdate ;
	
	RETURN('OK');

END;

END MAINTANCE_CLIENT;


CREATE OR REPLACE TRIGGER UPDATE_CLIENT_DATA
AFTER UPDATE ON CLIENT_DATA
FOR EACH ROW
DECLARE 
OldInformation varchar2(2000);


BEGIN

  IF :NEW.FIRSTNAME <> :OLD.FIRSTNAME THEN
	 OldInformation:= 'FIRSTNAME '||:OLD.FIRSTNAME;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.MIDDLENAME <> :OLD.MIDDLENAME THEN
	 OldInformation := 'MIDDLENAME '||:OLD.MIDDLENAME;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.LASTNAME <> :OLD.LASTNAME THEN
	 OldInformation := 'LASTNAME '||:OLD.LASTNAME;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.DATEOFBIRTH <> :OLD.DATEOFBIRTH THEN
	 OldInformation := 'DATEOFBIRTH '||:OLD.DATEOFBIRTH;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.CC_ID <> :OLD.CC_ID THEN
	 OldInformation := 'CC_ID '||:OLD.CC_ID;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.CC_EXPIRE_DATE <> :OLD.CC_EXPIRE_DATE THEN
	 OldInformation := 'CC_EXPIRE_DATE '||:OLD.CC_EXPIRE_DATE;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.VALID <> :OLD.VALID THEN
  	 OldInformation := 'VALID '||:OLD.VALID;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.INPUTDATE <> :OLD.INPUTDATE THEN
	 OldInformation := 'INPUTDATE '||:OLD.INPUTDATE;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.INPUTUSER <> :OLD.INPUTUSER THEN
  	 OldInformation := 'INPUTUSER '||:OLD.INPUTUSER;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.LASTMAINTDATE <> :OLD.LASTMAINTDATE THEN
	 OldInformation := 'LASTMAINTDATE '||:OLD.LASTMAINTDATE;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
  
  IF :NEW.LASTMAINTUSER <> :OLD.LASTMAINTUSER THEN
     OldInformation := 'LASTMAINTUSER '||:OLD.LASTMAINTUSER;
     INSERT INTO LOG_VALIDATION (LOG_ID,CLIENT_ID,CONTA_ID, MESSAGE, INPUTDATE, INPUTUSER )
	 VALUES (SQ_LOG_VALIDATION.NEXTVAL, :NEW.CLIENT_ID, NULL, 'OLD VALUE:'||OldInformation, SYSDATE, USER);
  END IF;
END;



